AppASM2/Areas/Staff/Controllers/ManageTraineeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppASM2.Controllers;
using AppASM2.Models;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AppASM2.Areas.Staff.Controllers
{
    [Authorize(Roles = "Staff")]
    public class ManageTraineeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/ManageUsers
        public ActionResult Index()
        {
            return View(db.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains("Trainee")).ToList());
        }

        // GET: Admin/ManageUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: Admin/ManageUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ManageUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: Admin/ManageUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Admin/ManageUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: Admin/ManageUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Admin/ManageUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppASM2/Areas/Trainee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="text-center">
        <img src="https://greenwich.edu.vn/images/config/logo_1454075749.png" class="rounded" alt="...">
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Greenwich", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Subject", "Index", "ManageTrainee")</li>
                    <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="p-3 mb-2 bg-info text-white">
            <div class="container">
                <center><h3 class="widget-title font-alt">Greenwich University Admissions Office</h3></center>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="widget">
                            <h4>HA NOI.</h4>
                            <p> DETECH Building -Number 8 Ton That Thuyet-My Dinh Ward 2-District Nam Tu Liem</p>
                            <p>Phone: 024.7300.2266</p>
                            <p>Hotline: 0981.558.080 | 0971,274,545</p>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget">
                            <h4>TP. HO CHI MINH.</h4>
                            <p> CS1: No. 142-146 Pham Phu Thu - Ward 4 - District 6 (End of Street 3/2)</p>
                            <p> CS2: 205 Nguyen Xi, Ward 26, Binh Thanh.</p>
                            <p>Phone: 028.7300.6622</p>
                            <p>Hotline: 0933.108.554 | 0971,294,545</p>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget">
                            <h4>DA NANG.</h4>
                            <p>658 Ngo Quyen, Son Tra district, Da Nang city</p>
                            <p>Phone: 0236.730.2266</p>
                            <p>Hotline: 0934.892.687</p>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget">
                            <h4>CAN THO.</h4>
                            <p>No. 160, 30/4 Street, An Phu Ward, Ninh Kieu District - City. Can Tho</p>
                            <p>Phone: 0292.730.0068</p>
                            <p>Hotline: 0968.670.804 | 0936,600,861</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="divider-d">
        <footer class="footer bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <p class="copyright font-alt">&copy; 2020&nbsp;<a>Hồ Anh Dũng</a>, Greenwich University</p>
                    </div>
                    <div class="col-sm-6">
                        <div class="container" style="text-align: center; padding: 10px;">
                            <a href="https://facebook.com/GreenwichVietnam" class="item-social"><img src="https://greenwich.edu.vn/templates/default/images/facebook.png" alt=""></a>
                            <a href="https://www.youtube.com/channel/UCO60geidjQPqSc6TH35YUEw" class="item-social"><img src="https://greenwich.edu.vn/templates/default/images/youtube.png" alt=""></a>
                            <a href="" class="item-social"><img src="https://greenwich.edu.vn/templates/default/images/google.png" alt=""></a>
                            <a href="https://www.instagram.com/uogvn/" class="item-social"><img src="https://greenwich.edu.vn/templates/default/images/instagram.png" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <div class="scroll-up"><a href="#totop"><i class="fa fa-angle-double-up"></i></a></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>